### ISSUE TITLE
Remove UTM zone/band guessing, raise error when globals not found.

### ISSUE THREAD

**Issue by KKalem** [smarc-project/smarc_missions#24]
I think it should always be an error if the globals are not there. We need the system to be predictable, not guess that it's gonna use something else. That's also the rationale for using global zones and bands, then we know what we are using everywhere.

_Originally posted by @nilsbore in https://github.com/smarc-project/smarc_missions/issues/23#issuecomment-728057684_

Effectively just remove the UTM zone/band calculations from the tree so that it only accepts these from the global rosparams.
The tree should refuse to work if these params are not present.

**Comment by nilsbore** [comment]
Nice touch with the quote :). Thanks for opening @KKalem

**Comment by KKalem** [comment]
f751e86 should have be doing this now. Will be tested tomorrow ;)

**Comment by nilsbore** [comment]
BTW, there is also a topic publishing lat/lon now, on `/vehicle/dr/lat_lon`. And services for converting back and forth between UTM and lat lon without knowing the zone and band.
