### ISSUE TITLE
topic names

### ISSUE THREAD

**Issue by NiklasRolleberg** [smarc-project/smarc_missions#29]
heartbeat: an empty message should be published to /lolo/core/heartbeat at 1hz or more

when a mission is done, an empty message should be published to /lolo/core/mission_complete to hand the control back to the captain

when abort is called, an empty message should be published to /lolo/core/abort

**Comment by nilsbore** [comment]
@KKalem Are you and Yi on this?

**Comment by KKalem** [comment]
Done even.
