### ISSUE TITLE
Mission complete

### ISSUE THREAD

**Issue by NiklasRolleberg** [smarc-project/smarc_missions#31]
Nothing is published on the topic /lolo/core/mission_complete when the vehicle reaches the last waypoint. Also in neptus, the vehicle mode doesn't change back to service from maneuver.

The test next week can still be done without fixing this, but if it is an easy fix it would be nice if at least the mission_complete part works.

**Comment by KKalem** [comment]
I believe this is fixed now. Re-open if still a problem.
